// Minimal modplatform stub
#ifndef MICROPY_INCLUDED_EXTMOD_MODPLATFORM_H
#define MICROPY_INCLUDED_EXTMOD_MODPLATFORM_H
#define MICROPY_PLATFORM_SYSTEM "VibeOS"
#define MICROPY_PLATFORM_VERSION ""
#endif
